[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: blob: https: *;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.supabase.co https://api.openai.com https://*.stripe.com https://*.mapbox.com https://*.google.com https://*.doubleclick.net https://*.adtrafficquality.google https://ep1.adtrafficquality.google;
      frame-src 'self' https://*.stripe.com https://*.google.com https://*.doubleclick.net;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      object-src 'none'
    """