[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.stripe.com https://*.supabase.co https://api.openai.com https://*.mapbox.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.mapbox.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co https://api.openai.com https://*.stripe.com https://*.mapbox.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.stripe.com https://pagead2.googlesyndication.com https://*.mapbox.com; frame-src 'self' https://*.stripe.com https://pagead2.googlesyndication.com;"