[build]
  command = "npm run build"
  publish = "dist"

# Note: Next.js plugin is disabled by not including it in the plugins section

[build.environment]
  NODE_VERSION = "18"

# Force HTTPS redirects - more aggressive
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Custom domain redirect (if needed)
# [[redirects]]
#   from = "https://mypartsrunner.com"
#   to = "https://mypartsrunner.com"
#   status = 200
#   force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers - enhanced
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co https://*.mapbox.com https://api.mapbox.com; img-src 'self' data: https://*.mapbox.com https://api.mapbox.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Force HTTPS for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/logo.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 